import { ArrowLeft, FileText, ShieldCheck } from "lucide-react";

const operatorFields = [
  ["Оператор", "ИП Шигапов Амир Фоатович"],
  ["ИНН", "165909137450"],
  ["ОГРНИП", "322169000048740"],
  ["Адрес", "г. Казань, ул. Мавлютова, д. 31а, оф. 2-7"],
  ["Email для обращений", "tokma2@yandex.ru"],
  ["Телефон", "+7 927 409-91-79"],
];

export default function Privacy() {
  return <main className="privacy-page"><header className="privacy-nav"><a className="galactic-brand" href="/"><span className="galactic-logo"><ShieldCheck size={17} /></span><span>Аре<span className="brand-accent">ал</span></span></a><a className="privacy-back" href="/"><ArrowLeft size={14} /> Вернуться на сайт</a></header><div className="privacy-page-inner"><div className="privacy-hero"><span className="privacy-icon"><FileText size={22} /></span><span className="section-eyebrow">ЮРИДИЧЕСКАЯ ИНФОРМАЦИЯ</span><h1>Политика конфиденциальности</h1><p>Риелторские услуги в Казани и Республике Татарстан · оператор — ИП Шигапов Амир Фоатович.</p></div><section className="privacy-page-card"><h2>1. Оператор персональных данных</h2><p>Оператором является лицо, указанное ниже. Он определяет цели и состав обработки персональных данных, а также отвечает на обращения субъектов данных.</p><div className="operator-grid">{operatorFields.map(([label, value]) => <div key={label}><small>{label}</small><b>{value}</b></div>)}</div><a className="privacy-site-link" href="https://shigapov-estate.ru/" target="_blank" rel="noreferrer">Официальный сайт оператора <ArrowLeft size={14} /></a></section><section className="privacy-page-card"><h2>2. Какие данные и зачем обрабатываются</h2><p>На сайте могут обрабатываться имя, номер телефона или Telegram, выбранный город, район, цель покупки, ипотечный сценарий, технические сведения об источнике перехода и UTM-метки. Цели обработки: ответ на запрос посетителя, подготовка подборки объектов, связь по заявке и оценка рекламных каналов.</p></section><section className="privacy-page-card"><h2>3. Правовое основание и срок</h2><p>Основанием является добровольное, конкретное, информированное и сознательное согласие субъекта персональных данных в соответствии со статьёй 9 Федерального закона №152-ФЗ «О персональных данных». Данные хранятся не дольше, чем необходимо для заявленных целей, если иной срок не установлен законом или договором.</p></section><section className="privacy-page-card"><h2>4. Передача и права субъекта</h2><p>Для обработки заявки данные могут передаваться уполномоченному сотруднику оператора через защищённый Telegram-канал. Субъект вправе запросить сведения об обработке, уточнение, блокирование или удаление данных, а также отозвать согласие, направив обращение оператору по указанным реквизитам.</p></section><section className="privacy-page-card"><h2>5. Cookies и рекламные метки</h2><p>Сайт может использовать Яндекс Метрику и UTM-метки для анализа посещаемости и эффективности рекламы. Подключение аналитики и состав уведомления о cookies должны быть согласованы с оператором до запуска рекламной кампании.</p></section><p className="privacy-source">Ориентир: статья 9 Федерального закона от 27.07.2006 №152-ФЗ. Эта страница не является юридическим заключением.</p></div></main>;
}
